/* Regenerates src/iconData.js from the icon names used anywhere in src/.
   Run with: npm run icons
   Add more sets by installing @iconify-json/<set> and listing it in SETS. */
const fs = require("fs");
const {getIconData} = require("@iconify/utils");

const SETS = ["devicon", "simple-icons", "logos", "skill-icons"];
const loaded = {};
for (const s of SETS) {
  try {
    loaded[s] = require(`@iconify-json/${s}/icons.json`);
  } catch (e) {
    /* set not installed - skip */
  }
}

// Scan every source file, not just portfolio.js - icon names also appear
// directly in components, e.g. <Icon icon="simple-icons:x" />.
function walk(dir) {
  return fs.readdirSync(dir, {withFileTypes: true}).flatMap(e => {
    const full = `${dir}/${e.name}`;
    if (e.isDirectory()) return walk(full);
    return full.endsWith(".js") ? [full] : [];
  });
}

const sources = walk("src")
  .filter(f => !f.endsWith("src/iconData.js"))
  .map(f => fs.readFileSync(f, "utf8"))
  .join("\n");

const names = [
  ...new Set([
    ...[...sources.matchAll(/iconifyIcon:\s*"([^"]+)"/g)].map(m => m[1]),
    ...[...sources.matchAll(/icon="([a-z0-9-]+:[a-z0-9-]+)"/g)].map(m => m[1])
  ])
];

const out = {};
const missing = [];
for (const full of names) {
  const [set, name] = full.split(":");
  const data = loaded[set] && getIconData(loaded[set], name);
  if (data) out[full] = data;
  else missing.push(full);
}

fs.writeFileSync(
  "src/iconData.js",
  "// Generated by `npm run icons` - do not edit by hand.\n" +
    "const ICONS = " + JSON.stringify(out) + ";\nexport default ICONS;\n"
);

console.log(`Inlined ${Object.keys(out).length} icon(s): ${Object.keys(out).join(", ")}`);
if (missing.length) {
  console.error(`MISSING (install @iconify-json/<set> or fix the name): ${missing.join(", ")}`);
  process.exit(1);
}
